# Fly.io configuration for Summ AI Web Frontend
# Documentation: https://fly.io/docs/reference/configuration/

app = "summ-ai-web"
primary_region = "gru"  # Sao Paulo, Brazil - change as needed

[build]
  # Use the Dockerfile in the apps/web directory
  dockerfile = "Dockerfile"
  # Build context is the project root
  build-context = "../.."

[env]
  NODE_ENV = "production"
  PORT = "3001"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# Auto-scaling configuration
[metrics]
  port = 3001
  path = "/metrics"
